t ?= esp32

TERMINAL_SPEED := 115200
CPPFLAGS = -DNO_STORAGE -DNO_SPIRAM -DTERMINAL_SPEED=$(TERMINAL_SPEED)
LIBRARIES = PS2KeyRaw SimpleTimer Adafruit_GFX Adafruit_BusIO Wire SPI

ifeq ($t, rp2040)
BOARD := adafruit_feather_dvi
flash := 8388608_0
#CPPFLAGS += -DDVI_BIT_DEPTH=1 -DDVI_RESOLUTION=DVI_RES_640x480p60
LIBRARIES += PicoDVI
endif

ifeq ($t, esp8266)
BOARD := d1_mini
baud := 921600
eesz := 4M

CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\"
LIBRARIES += TFT_eSPI
endif

ifeq ($t, esp32)
ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
LIBRARIES += ESP32Lib

else ifeq ($b, olimex)
BOARD := esp32-sbc-fabgl
SERIAL_PORT := /dev/ttyUSB0
CPPFLAGS += -DVGA_BIT_DEPTH=1 -DVGA_RESOLUTION=MODE640x480 -DVGA_DEFAULT_FONT=Font8x8
LIBRARIES += ESP32Lib

else
BOARD := lolin32
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp32-example.h\"
LIBRARIES += TFT_eSPI
endif
endif

include $t.mk
